# Generated by Django 5.2.8 on 2025-11-16 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ders Kodu')),
                ('name', models.CharField(max_length=255, verbose_name='Ders Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('instructor', models.CharField(blank=True, max_length=255, verbose_name='Eğitmen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Not Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('file', models.FileField(upload_to='notes/%Y/%m/%d/', verbose_name='Dosya')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Belgesi'), ('pptx', 'PowerPoint'), ('jpg', 'Resim (JPG)'), ('png', 'Resim (PNG)'), ('txt', 'Metin Dosyası'), ('other', 'Diğer')], max_length=10, verbose_name='Dosya Türü')),
                ('file_size', models.IntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('download_count', models.IntegerField(default=0, verbose_name='İndirilme Sayısı')),
                ('view_count', models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.course', verbose_name='Ders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Yıldız'), (2, '2 Yıldız'), (3, '3 Yıldız'), (4, '4 Yıldız'), (5, '5 Yıldız')], verbose_name='Puan')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Anonim mi?')),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Zorluk (1-5)')),
                ('workload', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='İş Yükü (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Ders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Değerlendiren Kullanıcı')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
